context("test: add_molecules")

test_that("Testing add molecule functionality", {

  # Test add_molecules input checks---------------------------------------------

  # Make an example molecule
  Molecule1 <- make_molecule(list("C" = 2, "H" = 4, "O" = -1))

  # All objects passed to add_molecules must be molecule_pspecter objects
  expect_error(
    add_molecules(Molecule1, list("C" = 3, "H" = 2)),
    "All inputs must be molecule_pspecter objects generated by make_molecule."
  )

  # CapNegative must be a true or false
  expect_error(
    add_molecules(Molecule1, CapNegatives = NA),
    "CapNegatives must be a TRUE or FALSE."
  )

  # Run the function------------------------------------------------------------

  # Add molecules with and without negatives capped
  AddMol1 <- add_molecules(Molecule1, Molecule1, CapNegatives = TRUE)
  AddMol2 <- add_molecules(Molecule1, Molecule1, CapNegatives = FALSE)

  # Double check formulas
  expect_equal(AddMol1$Formula, "C4H8")
  expect_equal(AddMol2$Formula, "C4H8O-2")

})
