context("test: sequence_plot")

test_that("Testing sequence plot plotting function", {

  # Download required test files------------------------------------------------

  source(system.file("tests/testthat/file_check.R", package = "pspecterlib"))
  downfolder <- file_check("downfolder")
  BU_ScanMetadata <- file_check("BU")
  BU_Peak <- get_peak_data(ScanMetadata = BU_ScanMetadata, ScanNumber = 31728)
  BU_Match <- readRDS(system.file("testdata", "BU_Match.RDS", package = "pspecterlib"))

  # Test sequence plot input checks---------------------------------------------

  # MatchedPeaks must be the correct object
  expect_error(
    sequence_plot(data.frame(test = 1)),
    "MatchedPeaks is not an object of the matched_peaks class generated by get_matched_peaks."
  )

  # IncludeIsotopes should be true or false
  expect_error(
    sequence_plot(BU_Match, IncludeIsotopes = NA),
    "IncludeIsotopes needs to be a single logical: a TRUE or FALSE."
  )

  # RemoveChargeAnnotation should be true or false
  expect_error(
    sequence_plot(BU_Match, RemoveChargeAnnotation = NA),
    "RemoveChargeAnnotation needs to be a single logical: a TRUE or FALSE."
  )

  # RemoveModification should be a single logical 
  expect_error(
    sequence_plot(BU_Match, RemoveModification = "cats"),
    "RemoveModification needs to be a single logical: a TRUE or FALSE"
  )
  
  # WrapLength should be an integer
  expect_error(
    sequence_plot(BU_Match, WrapLength = TRUE),
    "WrapLength must be a single integer."
  )

  # Make a sequence plot--------------------------------------------------------

  # Make one with charge annotations
  SeqPlot1 <- sequence_plot(BU_Match)
  expect_true(inherits(SeqPlot1, "ggplot"))

  # Make another without charge annotations
  SeqPlot2 <- sequence_plot(BU_Match, RemoveChargeAnnotation = TRUE)
  expect_true(inherits(SeqPlot2, "ggplot"))
  
  # Get a spectra with a modification
  BU_Match_Mod <- get_matched_peaks(PeakData = BU_Peak, 
                    AlternativeSequence = "IGA[Acetyl]VGGTENVSLTQSQMPAHNHLVAASTVSGTVKPLANDIIGAGLNK", 
                    AlternativeCharge = 5)
  SeqPlot3 <- sequence_plot(BU_Match_Mod)
  expect_true(inherits(SeqPlot3, "ggplot"))


})
