context("test: coverage_lit_seq_plot")

test_that("Testing coverage literature sequence plotting function", {

  # Download required test files------------------------------------------------

  source(system.file("tests/testthat/file_check.R", package = "pspecterlib"))
  downfolder <- file_check("downfolder")
  BU_ScanMetadata <- file_check("BU")
  ProteinTable <- readRDS(system.file("testdata", "ProteinTable.RDS", package = "pspecterlib"))
  PC <- readRDS(system.file("testdata", "PeptideCoverage.RDS", package = "pspecterlib"))

  # Test coverage lit seq plot input checks-------------------------------------

  # Peptide coverage must be of the correct class
  expect_error(
    coverage_lit_seq_plot(data.frame(test = 1)),
    "PeptideCoverage must be an object of the peptide_coverage class generated by get_peptide_coverage."
  )

  # Create a lit seq bar plot---------------------------------------------------

  # Try with a small sequence
  PC1 <- get_peptide_coverage(BU_ScanMetadata, ProteinTable, "SO_0252")
  litseqplot1 <- coverage_lit_seq_plot(PC1)
  expect_true(inherits(litseqplot1, "ggplot"))

  # Try with a medium sequence
  PC2 <- get_peptide_coverage(BU_ScanMetadata, ProteinTable, "SO_0201")
  litseqplot2 <- coverage_lit_seq_plot(PC2)
  expect_true(inherits(litseqplot2, "ggplot"))

  # Try with a large sequence
  PC3 <- get_peptide_coverage(BU_ScanMetadata, ProteinTable, "SO_0130")
  litseqplot3 <- coverage_lit_seq_plot(PC3)
  expect_true(inherits(litseqplot3, "ggplot"))

  # Try with a very large sequence
  litseqplot <- coverage_lit_seq_plot(PC)
  expect_true(inherits(litseqplot, "ggplot"))

})
