#' Adds Molecule Dataframes, Helper Function to get_peptide_coverage
#'
#' @description This simple function allows for two molecule data frames from make_molecule to be added together
#'
#' @param ... Any number of molecules from the make_molecule class
#' @param CapNegatives A TRUE/FALSE to indicate whether negative elements should be
#'     capped at 0. Useful for modifications where elements are lost. Default is TRUE.
#'
#' @details
#' Returns a molecule dataframe which is the summation of the provided molecule dataframes
#'
#' @examples
#' \dontrun{
#'
#' # Add two molecules together
#' add_molecules(
#'   make_molecule(AtomList = list("C" = 2, "H" = 3, "O" = 1, "P" = 0)),
#'   make_molecule(AtomList = list("C" = 1, "H" = 4, "O" = 0, "N" = 1)),
#'   make_molecule(AtomList = list("C" = 6))
#' )
#'
#' }
#'
#' @export
add_molecules <- function(..., CapNegatives = TRUE) {

  ##################
  ## CHECK INPUTS ##
  ##################

  # Check for extra molecules
  molecule_objects <- list(...)

  # Iterate through all combinations and determine that it is an object of the
  # molecule_pspecter class
  ObjectTest <- lapply(molecule_objects, function(molecule) {
    inherits(molecule, "molecule_pspecter")
  }) %>% unlist() %>% all()

  # Check that all objects are molecule_pspecter objects
  if (ObjectTest == FALSE) {
    stop("All inputs must be molecule_pspecter objects generated by make_molecule.")
  }

  # Check that CapNegatives is a TRUE or FALSE
  if (!is.logical(CapNegatives) | is.na(CapNegatives)) {
    stop("CapNegatives must be a TRUE or FALSE.")
  }

  ########################
  ## BUILD ADDED OBJECT ##
  ########################

  # Create list of atoms of molecular formulas added together
  AtomList <- do.call(dplyr::bind_rows, lapply(molecule_objects, function(mol) {
    class(mol) <- "data.frame"
    mol %>% dplyr::select(-Formula)
  })) %>%
    colSums(na.rm = T) %>%
    as.list()

  # Remove anything less than 0
  if (CapNegatives) {
    AtomList <- AtomList[AtomList > 0]
  }

  # Return the molecule
  return(make_molecule(AtomList))

}
